apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maintenance-agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get","update","list","watch"]
- apiGroups: ["ramendr.openshift.io"]
  resources: ["maintenancemodes","maintenancemodes/status"]
  verbs: ["get", "list","watch","update", "patch"]
- apiGroups: ["ceph.rook.io"]
  resources: ["cephclusters"]
  verbs: ["get", "watch", "list"]