apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: mirrorpeer-sample
spec:
  items:
    - clusterName: local-cluster
      storageClusterRef:
        name: ocs-storagecluster
        namespace: openshift-storage
    - clusterName: spoke-cluster
      storageClusterRef:
        name: ocs-storagecluster
        namespace: openshift-storage
  schedulingIntervals: ["5m"]
  manageS3: false